package com.exam.login.util

import com.exam.login.R
import com.exam.login.model.Shoe

object TempData {
    val shoeList : ArrayList<Shoe> = arrayListOf(
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoe-WrLlWX.png","Best Seller","Nike Air Force1","Men's Shoe","$149","The radiance lives on in the Nike Air Force 1 '07, the b-ball OG that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ad790e31-a926-43a8-9463-bc29a4e25cca/zoom-lebron-3-shoes-2pZS67.png","Just In","Nike Zoom LeBron 3","Men's Shoe","$275","Stay sharp in the Nike Zoom LeBron 3. Classic red, white and blue accents celebrate those trusted barbershops that keep you looking fresh. Metallic details, nodding to the tools of the trade, polish your outfit. And finishing it off, Zoom Air cushioning delivers more comfort than a hot towel service."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/f2ff7f7a-0e13-4148-8eb4-60b83e86f99b/air-force-1-07-lv8-shoes-BS9f21.png","Just In","Air Force 1'07 LV8","Men's Shoe","$179","We just want to say, \"HAVE A NIKE DAY\". The radiance lives on with the b-ball original. Crossing hardwood comfort with off-court flair, it puts a friendly spin on what you know best: era-echoing, '80s construction, bold details and nothin'-but-net style."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/886f7028-d0c3-432e-800b-0ac6e5b84c16/air-max-90-shoes-kRsBnD.png","Just In","Nike Air Max 90","Men's Shoe","$205","Lace up and feel the legacy. Produced at the cross-section of art, music and culture, this champion running shoe helped define the '90s. Worn by presidents, revolutionised through collabs and celebrated through rare colourways, its striking visuals, Waffle outsole and exposed Air cushioning keep it alive and well."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/e5f759bb-0f89-4fbe-ab21-bea2190c96e9/air-max-97-se-shoes-LJVTjv.png","Just In","Nike Air Max 97 SE","Men's Shoe","$265","Legend has it the original Air Max 97 was inspired by Tokyo's lightning-fast public transport system. Nicknamed the \"silver bullet\", they were truly the shoes of the future thanks to innovative full-length Air cushioning and a sleek design. Write the next chapter with this modern version."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/a6d7b4cd-83d0-4c61-b0ed-8a7b32ac48e8/nocta-hot-step-air-terra-shoe-SZ40xX.png","Just In","NOCTA Hot Step Air Terra","Men's Shoe","$229","Take your game anywhere. From hoops to trails to the street, the NOCTA Hot Step Air Terra brings opportunity. Quilted panels are crafted with premium leather. Trusted Air cushioning delivers performance comfort. Rugged tread on the rubber outsole adds traction."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/42a80552-7c69-4f22-b86b-bdd8e16f3d8a/custom-nike-phantom-gt-elite-by-you.png","Member Access","Phantom Ft Elite","Men's Shoe","$399","Nike's first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270.The design draws inspiration from Air Max icons, showcasing Nike's greatest innovation with its large window and fresh array of colours."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/d7f15fff-771d-41f6-acb5-fa921342115b/jordan-1-ko-shoes-RLJcHC.png","Just In","Jordan 1 Ko","Men's Shoe","$219","The Jordan 1 inspires admiration among collectors and next-gen fans alike.The Jordan 1 KO repackages the famous icon using a mix of synthetic leather and canvas, with a fit that's redesigned for comfort."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/4298f565-3393-44ef-b54f-c14e78b6c2de/ecohaven-next-nature-slides-zkNh14.png","Sustaninable Materials","EcoHaven Next Nature","Men's Slides","$75","The Nike EcoHaven Slide—wear it all day, in wet or dry conditions, from the beach to the boardwalk and everywhere in between. Its Crater Foam delivers amazing step-in comfort. Nike Grind helps keep your foot from slipping. The durable tech-cord strap feels great and adds an outdoorsy vibe. To top it off, we've made it from at least 20% recycled materials by weight. So get out there and do good by looking good."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/a73abbc4-d1a5-425d-b341-927d4b1ada96/victori-one-slide-QTTJHP.png","Bestseller","Nike Victori One","Men's Slides","$49","From the beach to the bleachers, the Nike Victori One perfects a classic, must-have design. Delivering lightweight comfort that's easy to wear, it's updated with softer, more responsive foam. The contoured grip pattern helps cradle and hold your foot in place while the new padded strap feels as good as it looks."),

        Shoe("https://static.nike.com/a/images/t_prod_ss/w_640,c_limit,f_auto/57bbdd11-054f-43b6-91ab-bf61d37b6781/women-s-dunk-low-rose-whisper-dd1503-118-release-date.jpg","Available in SNKRS","Nike Dunk Low","Womem's Shoes","$159","Originally created for the hardwood, the Dunk later took to the streets—and as they say, the rest is history. More than 35 years after its debut, the silhouette still delivers bold, defiant style and remains a coveted look for crews across both sport and culture. Now, the college hoops original is refreshed with a softer palette. Rose Whisper and white colour blocking delivers seasonal style and a bright—but still subtle—touch to your outfit."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/18998629-57f0-4ad5-a39e-489e4c24f8c9/custom-nike-air-force-1-unlocked-by-you.png","","Air Force1 Low by You","Womem's Shoes","$229","This product is custom-made and delivered to you in 5 weeks or less.") ,
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ce9df7bd-a2bf-4e1e-95f1-95d633cf0389/offcourt-slides-kJDhS7.png","Bestseller","Nike Offcourt","Women's Slides","$59","Featuring Revive Foam, a super-soft foam designed to help you relax and recharge, the unrelenting comfort of the Nike Offcourt Slide is sensational.The innovative dual-layered foam and soft jersey lining on the strap ensure a gratifying full-foot experience.The iconic Air Force 1 pivot circle outsole and block lettering on the strap casually nod to heritage hoops."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/3285da6e-6008-4957-842e-8f10d48beee5/air-max-95-shoes-TJH2bZ.png","Member Access","Nike air Max 95","Women's Shoes","$219","Taking inspiration from the human body and '90s athletics aesthetics, the Nike Air Max 95 mixes unbelievable comfort with head-turning style. The iconic side panels represent strength and use a selection of colours. Visible Air in the heel and forefoot cushions every step."),
        Shoe("https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/804a1024-bf36-4ba9-abde-4d7f89731051/victori-one-print-slide-cz4wps.png","Bestseller","Nike Victori One","Womem's Slides","$59","From the beach to the streets, the Nike Victori One perfects a classic, must-have design. Delivering lightweight comfort that's easy to wear, it features new, softer foam that feels comfortable. The contoured footbed with grip pattern helps cradle and hold your foot in place. The wide, padded strap feels as good as it looks."),

        )
}